Book_my_show/Book_my_show/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("users/", include("users.urls")),
    path("admin_dashboard/", include("admin_dashboard.urls")),
    path("theatre/", include("theatre.urls")),
    path("chatapp/", include("chatapp.urls")),
    path("room/", include("room.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Book_my_show/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("all_movies/", views.all_movies, name="all_movies"),
    path("search/", views.search, name="search"),
    path("about/", views.about, name="about"),
    path("movie/<int:id>", views.movie, name="movie"),
    path("cinemas/", views.cinemas, name="cinemas"),
    path("list_movies/<int:id>/", views.list_movies, name="list_movies"),
    path("theatre_choose/<int:id>", views.theatre_choose, name="theatre_choose"),
    path(
        "seat_selection/<int:theatre_id>/<int:screen_id>/<int:show_time_id>/<str:selected_date>/",
        views.seat_selection,
        name="seat_selection",
    ),
    path("payment/", views.payment, name="payment"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
    path("user_logout/", views.user_logout, name="user_logout"),
]

Book_my_show/theatre/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path("theatre_home", views.theatre_home, name="theatre_home"),
    path("theatre_movies", views.theatre_movies, name="theatre_movies"),
    path("theatre_screen", views.theatre_screen, name="theatre_screen"),
    path("add_screen", views.add_screen, name="add_screen"),
    path("update_screen/<int:id>", views.update_screen, name="update_screen"),
    path("delete_screen/<int:id>", views.delete_screen, name="delete_screen"),
    path(
        "theatre_side_booking", views.theatre_side_booking, name="theatre_side_booking"
    ),
    path(
        "theatre_generate_excel",
        views.theatre_generate_excel,
        name="theatre_generate_excel",
    ),
    path(
        "cancellation_requests",
        views.cancellation_requests,
        name="cancellation_requests",
    ),
    path(
        "update_cancellation_request",
        views.update_cancellation_request,
        name="update_cancellation_request",
    ),
    path("theatre_profile", views.theatre_profile, name="theatre_profile"),
    path("theatre_logout/", views.theatre_logout, name="theatre_logout"),
]

Book_my_show/theatre/models.py
from django.db import models
from django.contrib.auth.models import User
from admin_dashboard.models import Movies
from home.models import *
from django.utils import timezone
from datetime import datetime
import uuid
from .models import *

# Create your models here.


class Show_Time(models.Model):
    time = models.TimeField()

    def __str__(self):
        time_obj = datetime.strptime(self.time, "%H:%M:%S").time()
        return time_obj.strftime("%I:%M%p")


class Screen(models.Model):
    theatre = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    price1 = models.DecimalField(max_digits=6, decimal_places=2)
    price2 = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    price3 = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    movies = models.ForeignKey(Movies, on_delete=models.CASCADE)
    show_times = models.ManyToManyField(Show_Time)
    total_seat_rows = models.IntegerField(default=None)
    total_seat_columns = models.IntegerField(default=None)

    def __str__(self) -> str:
        return f"{self.name} - {self.theatre.user}"


def get_default_booked_time():
    return timezone.now().time()


def get_default_booked_date():
    return timezone.now().date()


class BookedSeat(models.Model):
    booking_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.CharField(max_length=255, default=None)
    movie = models.CharField(max_length=30, default=None)
    movie_poster = models.ImageField(upload_to="booked_movie_images", blank=True)
    email = models.EmailField(max_length=50)
    phone = PhoneNumberField(null=True, blank=False, default=None)
    theatre = models.CharField(max_length=255, default=None)
    screen = models.CharField(max_length=255, default=None)
    booked_seats = models.CharField(max_length=255, default=None)
    count = models.PositiveIntegerField(default=0)
    price = models.IntegerField(default=None)
    date = models.CharField(max_length=20)
    show_time = models.CharField(max_length=255, default="")
    payment_order_id = models.CharField(max_length=100, default=None)
    payment_id = models.CharField(max_length=100, default=None, null=True)
    booked_date = models.DateField(default=get_default_booked_date)
    booked_time = models.TimeField(default=get_default_booked_time)

    def set_booked_seats(self, integer_list):
        self.booked_seats = ",".join(str(i) for i in integer_list)

    def get_booked_seats(self):
        return [int(i) for i in self.booked_seats.split(",")]

    def __str__(self):
        return str(self.booking_id)


class Theatre_Sale_Report(models.Model):
    name = models.CharField(max_length=255, default=None)
    booking = models.ForeignKey(BookedSeat, on_delete=models.CASCADE)
    theatre_earnings = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00
    )
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Admin_Sale_Report(models.Model):
    name = models.CharField(max_length=255, default=None)
    theatre_sale_report = models.ForeignKey(
        Theatre_Sale_Report, on_delete=models.CASCADE
    )
    admin_earnings = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.name

Book_my_show/home/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget


class UserProfileForm(forms.ModelForm):
    # Fields from UserProfile model
    profile_image = forms.ImageField()
    phone = PhoneNumberField(widget=PhoneNumberPrefixWidget)
    address = forms.CharField(max_length=50)
    location = forms.CharField(max_length=30)

    # Fields from User model
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    username = forms.CharField(max_length=25)
    email = forms.EmailField(max_length=50)

    class Meta:
        model = UserProfile
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "profile_image",
            "phone",
            "address",
            "location",
        ]


class AdminProfileForm(forms.ModelForm):
    # Fields from User model
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    username = forms.CharField(max_length=25)
    email = forms.EmailField(max_length=50)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email"]

Book_my_show/theatre/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.decorators import login_required
from admin_dashboard.models import *
from home.models import UserProfile
from users.models import *
from django.http import JsonResponse
from Book_my_show.settings import KEY, SECRET
from home.forms import *
import razorpay, json
from decimal import Decimal
from datetime import date, timedelta, datetime
from django.db.models import Sum
from django.utils import timezone
import decimal
from django.http import HttpResponse
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font
import openpyxl
from django.core.paginator import Paginator

# Create your views here.


def theatre_home(request):
    if "user" in request.session:
        return redirect("home")
    if "admin" in request.session:
        return redirect("admin_home")
    if "theatre" in request.session:
        # Get today's date
        today = date.today()

        # Get the start and end dates for the current month
        start_of_month = today.replace(day=1)
        end_of_month = start_of_month.replace(
            month=start_of_month.month + 1
        ) - timedelta(days=1)

        # Calculate the total sale price for today
        today_total_price = (
            Theatre_Sale_Report.objects.filter(
                name=request.user,
                date_added__year=today.year,
                date_added__month=today.month,
                date_added__day=today.day,
            ).aggregate(total_price=Sum("booking__price"))["total_price"]
            or 0.00
        )

        today_total_revenue = (
            Theatre_Sale_Report.objects.filter(
                name=request.user,
                date_added__year=today.year,
                date_added__month=today.month,
                date_added__day=today.day,
            ).aggregate(total_price=Sum("theatre_earnings"))["total_price"]
            or 0.00
        )

        # Calculate the sales and revenue data for each day of the week
        sales_data = []
        revenue_data = []
        days_of_week = []

        for i in range(7):
            # Get the date for the corresponding day of the week
            day = today - timedelta(days=today.weekday()) + timedelta(days=i)
            days_of_week.append(day.strftime("%a"))

            # Calculate the total sale price for the day
            day_total_price = (
                Theatre_Sale_Report.objects.filter(
                    name=request.user,
                    date_added__year=day.year,
                    date_added__month=day.month,
                    date_added__day=day.day,
                ).aggregate(total_price=Sum("booking__price"))["total_price"]
                or 0.00
            )
            sales_data.append(day_total_price)

            # Calculate the total revenue for the day
            day_total_revenue = (
                Theatre_Sale_Report.objects.filter(
                    name=request.user,
                    date_added__year=day.year,
                    date_added__month=day.month,
                    date_added__day=day.day,
                ).aggregate(total_price=Sum("theatre_earnings"))["total_price"]
                or 0.00
            )
            revenue_data.append(day_total_revenue)

        sale_reports = Theatre_Sale_Report.objects.filter(name=request.user)

        # Calculate the total sale price for this month
        month_total_price = (
            Theatre_Sale_Report.objects.filter(
                name=request.user, date_added__range=(start_of_month, end_of_month)
            ).aggregate(total_price=Sum("booking__price"))["total_price"]
            or 0.00
        )

        month_total_revenue = (
            Theatre_Sale_Report.objects.filter(
                name=request.user, date_added__range=(start_of_month, end_of_month)
            ).aggregate(total_price=Sum("theatre_earnings"))["total_price"]
            or 0.00
        )
        print(
            "sales_data:",
            sales_data,
            "revenue_data:",
            revenue_data,
            "days_of_week:",
            days_of_week,
        )
        revenue_data = [
            float(value) if isinstance(value, decimal.Decimal) else value
            for value in revenue_data
        ]
        context = {
            "sale_reports": sale_reports,
            "today_total_price": today_total_price,
            "month_total_price": month_total_price,
            "today_total_revenue": today_total_revenue,
            "month_total_revenue": month_total_revenue,
            "sales_data": sales_data,
            "revenue_data": revenue_data,
            "days_of_week": days_of_week,
        }
        return render(request, "theatre/theatre_home.html", context)
    else:
        return redirect("home")


def theatre_movies(request):
    if "user" in request.session:
        return redirect("home")
    if "admin" in request.session:
        return redirect("admin_home")
    if "theatre" in request.session:
        movies = Movies.objects.all()
        items_per_page = 4
        paginator = Paginator(movies, items_per_page)
        page_number = request.GET.get("page")
        page = paginator.get_page(page_number)
        return render(
            request, "theatre/theatre_movies.html", {"movies": movies, "page": page}
        )
    else:
        return redirect("home")


def theatre_screen(request):
    if "user" in request.session:
        return redirect("home")
    if "admin" in request.session:
        return redirect("admin_home")
    if "theatre" in request.session:
        # screens=Screen.objects.filter(theatre_id=request.user.id)
        user_profile = UserProfile.objects.get(user=request.user)
        screens = Screen.objects.filter(theatre=user_profile)
        items_per_page = 4
        paginator = Paginator(screens, items_per_page)
        page_number = request.GET.get("page")
        page = paginator.get_page(page_number)
        print("theatre_id", request.user.id)
        return render(
            request, "theatre/theatre_screen.html", {"screens": screens, "page": page}
        )
    else:
        return redirect("home")


def add_screen(request):
    if "user" in request.session:
        return redirect("home")
    if "admin" in request.session:
        return redirect("admin_home")
    if "theatre" in request.session:
        if request.method == "POST":
            # print('logged in username:',request.user)

            name = request.POST.get("name")
            price1 = request.POST.get("price1")
            price2 = request.POST.get("price2") or None
            price3 = request.POST.get("price3") or None
            movies_id = request.POST.get("movie")
            rows = request.POST.get("rows")
            columns = request.POST.get("columns")
            show_times = request.POST.getlist("show_times[]")

            theatre = UserProfile.objects.get(user=request.user)
            movies = Movies.objects.get(id=movies_id)
            screen = Screen.objects.create(
                theatre=theatre,
                name=name,
                price1=price1,
                price2=price2,
                price3=price3,
                movies=movies,
                total_seat_rows=rows,
                total_seat_columns=columns,
            )
            for show_time_str in show_times:
                show_time_obj = Show_Time.objects.create(time=show_time_str)
                screen.show_times.add(show_time_obj)
            screen.save()
            return redirect("theatre_screen")
        else:
            movies = Movies.objects.all()
            # shows=Show_Time.objects.all()
            return render(request, "theatre/add_screen.html", {"movies": movies})
    else:
        return redirect("home")


def update_screen(request, id):
    if "user" in request.session:
        return redirect("home")
    if "admin" in request.session:
        return redirect("admin_home")
    if "theatre" in request.session:
        screen = Screen.objects.get(id=id)
        if request.method == "POST":
            theatre = UserProfile.objects.get(user=request.user)
            name = request.POST.get("name")
            price1 = request.POST.get("price1")
            price2 = request.POST.get("price2") or None
            price3 = request.POST.get("price3") or None
            movies_id = request.POST.get("movie")
            rows = request.POST.get("rows")
            columns = request.POST.get("columns")
            existing_show_times = request.POST.getlist("existing_show_times[]")
            movies = Movies.objects.get(id=movies_id)

            # Update existing screen details
            screen.theatre = theatre
            screen.name = name
            screen.price1 = price1
            screen.price2 = price2
            screen.price3 = price3
            screen.movies = movies
            screen.total_seat_rows = rows
            screen.total_seat_columns = columns

            # Remove deselected show_times from the screen
            deselected_show_times = screen.show_times.exclude(
                id__in=existing_show_times
            )
            for show_time in deselected_show_times:
                screen.show_times.remove(show_time)

            # Add the selected show_times to the screen
            for show_time_id in existing_show_times:
                show_time = Show_Time.objects.get(id=show_time_id)
                screen.show_times.add(show_time)

            # Create new show_times and add them to the screen
            new_show_times = request.POST.getlist("show_times[]")
            for show_time_str in new_show_times:
                show_time_obj = Show_Time.objects.create(time=show_time_str)

Book_my_show/templates/theatre/add_screen.html
{% extends 'base1.html' %}
{% load static %}
{% block admin_page %}



<style>
    .form-control{
        width:140%;
    }
</style>
        <!-- Form Start -->
        <div class="container-fluid pt-4 px-4">
          <div class="row g-4">
              <div class="col-sm-12 col-xl-7" style="margin-left:13%">
                  <div class="bg-light rounded h-100 p-4" style="width:100%">
                      <h6 class="mb-4">Add Screen</h6>
                      <form action="" method="post" enctype="multipart/form-data">
                          {% csrf_token %}
                          <div style="display:flex">
                              <div class="col-sm-12 col-xl-6" style="margin-right:1rem">
                                  <!-- Your existing form fields -->
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">NAME</label>
                                            <input type="text" class="form-control" id="title" name="name" placeholder="Screen Name"
                                                aria-describedby="emailHelp" required>
                                        </div>
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">NORMAL</label>
                                            <input type="number" class="form-control" id="title" name="price1" placeholder="Normal Price"
                                                aria-describedby="emailHelp" required>
                                        </div>
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">EXECUTIVE</label>
                                            <input type="number" class="form-control" id="title" name="price2" placeholder="Executive Price"
                                                aria-describedby="emailHelp">
                                        </div>
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">PREMIUM</label>
                                            <input type="number" class="form-control" id="title" name="price3" placeholder="Premium Price"
                                                aria-describedby="emailHelp">
                                        </div>
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">MOVIE</label>
                                            <select class="form-select" id="floatingSelect" name="movie"
                                                aria-label="Floating label select example" required>
                                                <option selected></option>
                                                {% for mov in movies %}
                                                <option value="{{mov.id}}">{{mov.title}}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">No. Of Rows</label>
                                            <input type="number" class="form-control" id="title" name="rows" placeholder="Total No.Of Rows"
                                                aria-describedby="emailHelp">
                                        </div>
                                        <div class="mb-3">
                                            <label for="exampleInputEmail1" class="form-label">No. Of Columns</label>
                                            <input type="number" class="form-control" id="title" name="columns" placeholder="Total No.Of Columns"
                                                aria-describedby="emailHelp">
                                        </div>
                                        <div class="mb-3">
                                          <label for="exampleInputEmail1" class="form-label">SHOW TIMES</label>
                                          <div id="show-times-container">
                                              <div class="show-time-group mb-2">
                                                  <input type="time" class="form-control" name="show_times[]" required>
                                                  <button type="button" class="btn btn-link remove-show-time">Remove</button>
                                              </div>
                                          </div>
                                          <button type="button" class="btn btn-primary" id="add-show-time">Add Show Time</button>
                                      </div>

                                    <!-- Your existing form fields -->

                                </div>
                            </div>
                            <div align="center">
                                <button type="button" class="btn btn-primary" id="submit-form">ADD</button>
                                <a href="{% url 'theatre_screen' %}" class="btn btn-danger">CANCEL</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Form End -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <script>
          $(document).ready(function() {
            console.log("Document ready!");
              $("#add-show-time").on('click', function() {
                  $("#show-times-container").append(
                      '<div class="show-time-group mb-2">' +
                      '<input type="time" class="form-control" name="show_times[]" required>' +
                      '<button type="button" class="btn btn-link remove-show-time">Remove</button>' +
                      '</div>'
                  );
              });
      
              $(document).on('click', '.remove-show-time', function() {
                  $(this).closest('.show-time-group').remove();
              });
      
              $("#submit-form").on('click', function() {
                  $("form").submit();
              });
          });
      </script>

{% endblock %}

Book_my_show/templates/theatre/delete_screen.html
{% extends 'base1.html' %}
{% load static %}
{% block admin_page %}
            <!-- 404 Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="row vh-100 bg-light rounded align-items-center justify-content-center mx-0">
                    <div class="col-md-6 text-center p-4">

                        <form method="POST" action="">
                            {% csrf_token %}
                            <h4>Are you sure you want to delete this?</h4>
                            <button type="submit" class="btn btn-danger">Yes</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- 404 End -->
{% endblock %}

Book_my_show/templates/theatre/theatre_profile.html
{% extends 'base1.html' %}
{% load static %}
{% block admin_page %}



<!-- Table Start -->
<div class="container-fluid pt-4 px-2" style="min-height:80vh;margin-left:-20px">
    <div class="row g-4">
        <div class="col-12">
            <div class="bg-light rounded h-100 p-4">
                <div class="row">
                    <div class="col-md-3 border-right">
                        {% if user_profile.profile_image %}
                            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" style="border-radius:50%" src="{{user_profile.profile_image.url}}"><br>
                        {% else %}
                            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="{% static 'images/user_icon.png' %}"><br>
                        {% endif %}<br>
                        <strong><span class="font-weight-bold">{{user_profile.user.first_name}}  {{user_profile.user.last_name}}</span><br></strong>
                        <span class="font-weight-bold">{{user_profile.user.username}}</span><br>
                        <span class="text-black-50">{{user_profile.user.email}}</span><br>
                        <span>{{user_profile.phone}}</span><br>
                        <span>{{user_profile.address}}</span><br>
                        <span>{{user_profile.location}}</span><br>
                    </div>
                    </div>
                    <div class="col-md-5 border-right">
                        <form action="{% url 'theatre_profile' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="p-3 py-5">
                                <div class="d-flex justify-content-between align-items-center mb-5">
                                    <h4 class="">Profile Settings</h4>
                                </div><br>
                        
                                <div class="row mt-5">
                                    <div class="col-md-6" >
                                        <div class="form-group">
                                            <label class="labels" for="id_first_name">First Name</label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="labels" for="id_last_name">Last Name</label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                        
                                <div class="row mt-3">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="labels" for="id_profile_image">Profile Picture</label>
                                            {{ form.profile_image }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="labels" for="id_phone">Mobile Number</label>
                                            {{ form.phone }}
                                        </div>
                                    </div>
                                </div>
                        
                                <div class="row mt-3">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="labels" for="id_username">User Name</label><br>
                                            {{ form.username }}
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="labels" for="id_email">Email ID</label><br>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    
                                
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="labels" for="id_address">Address</label><br>
                                            {{ form.address }}
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="labels" for="id_location">Location</label><br>
                                            {{ form.location }}
                                        </div>
                                    </div>
                                </div>
                        
                                <div class="mt-5 text-center">
                                    <button class="btn btn-primary profile-button" type="submit">Update Profile</button>
                                </div>
                            </div>
                        </form>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Table End -->

{% endblock %}